# Generated by Django 4.1.7 on 2023-06-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('question', models.CharField(max_length=500, null=True)),
                ('Answer', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Excurisons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_name', models.CharField(max_length=50, null=True)),
                ('E_Desc', models.CharField(max_length=20, null=True)),
                ('E_Price', models.CharField(max_length=20)),
                ('E_link', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=50, null=True)),
                ('F_Desc', models.CharField(max_length=20, null=True)),
                ('F_Price', models.CharField(max_length=20, null=True)),
                ('F_link', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_name', models.CharField(max_length=50, null=True)),
                ('H_Desc', models.CharField(max_length=20, null=True)),
                ('H_Price', models.CharField(max_length=20, null=True)),
                ('H_link', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('attend', models.CharField(choices=[('yes', 'Yes, I will be attending'), ('no', 'No, I will not be attending')], max_length=3)),
            ],
        ),
    ]
